### ISSUE TITLE
Can't access dataset

### ISSUE THREAD

**Issue by mofadic** [PhilJd/freiburg_groceries_dataset#3]
Hello, last week I had no issue connecting to [the dataset link](http://aisdatasets.informatik.uni-freiburg.de/freiburg_groceries_dataset/), but at least since yesterday the link fails with ERR_CONNECTION_TIMED_OUT.

Is this a temporary issue? Was the dataset relocated?

Best regards.

**Comment by PhilJd** [comment]
Hi @mofadic,
this should be a temporary issue due to server maintenance today and on Thursday. Please let me know if the issue persists after Thursday. Sorry for the inconvenience!
Cheers

**Comment by mofadic** [comment]
Hi @PhilJd, the site is available again.
Thanks for your quick answer.
